#!/bin/bash
#
#    20-zkitupdate - generate ZeroKit update information
# 	 Copyright (c) 2017 Tresorit AG.
#
#    Authors: Gergely Hamos &lt;hamos@tresorit.com&gt;
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License along
#    with this program; if not, write to the Free Software Foundation, Inc.,
#    51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

curl https://api.github.com/repos/tresorit/ZeroKit-NodeJs-backend-sample/git/refs/heads/master --max-time 2 2>&1 | grep -s "\"sha\":" | grep -q -v $(git -C /var/www/zerokit/ rev-parse HEAD 2>&1) && echo "Backend sample can be updated, please use 'zkitadm upgrade' command"
curl https://api.github.com/repos/tresorit/ZeroKit-Azure-marketplace-vm/git/refs/heads/master --max-time 2 2>&1 | grep -s "\"sha\":" | grep -q -v $(git -C /opt/zerokit/ rev-parse HEAD 2>&1) && echo "Zkitadm utility can be updated, please use 'zkitadm upgrade' command"

exit 0

